name: Dotnetapplication

on:
  workflow_dispatch:
  push:
    branches:
    - master


jobs:
  DotnetInstall:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Dotnet install
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          
  # Install_dependencies:
  #   runs-on: ubuntu-latest
  #   needs: DotnetInstall
  #   steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v4
       # - name: Installing dependency
       #   run: dotnet restore
          
        
  
