name: Dotnetapplication

on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - master

jobs:
  DotnetInstall:
    name: Run dotnet on Ubuntu
    runs-on: self-hosted
    steps:
      - name: install dotnet using CLI way
        run: |
          wget https://download.visualstudio.microsoft.com/download/pr/b521d7d2-108b-43d9-861a-58b2505a125a/0023553690a68328b33bc30a38f151db/dotnet-sdk-6.0.420-linux-x64.tar.gz
          mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-6.0.420-linux-x64.tar.gz -C $HOME/dotnet
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$PATH:$HOME/dotnet
          dotnet --version
          
  # Install_dependencies:
  #   runs-on: ubuntu-latest
  #   needs: DotnetInstall
  #   steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v4
  #      - name: Installing dependency
  #        run: dotnet restore

  # Build_dotnet:
  #   runs-on: ubuntu-latest
  #   needs: Install_dependencies
  #   steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v4
  #      - name: Installing dependency
  #        run: dotnet build --configuration Release
      
  # Publish_dotnet:
  #     runs-on: ubuntu-latest
  #     needs: Build_dotnet
  #     steps:
  #        - name: Checkout code
  #          uses: actions/checkout@v4
  #        - name: Installing dependency
  #          run: dotnet publish --configuration Release  
           
  #        - name: UploadArtifact
  #          uses: actions/upload-artifact@v4.3.1
  #          with:
  #            name: dotnetdll
  #            path: bin/Release/netcoreapp3.1/TodoApi.dll

  # Build_image:
  #   runs-on: ubuntu-latest
  #   needs: Publish_dotnet
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Download Dll file
  #       run: gh run download ${{ github.run_id }}
  #     - name: Build Docker image
  #       run: |
  #         docker build -t demodotnet:${{ github.run_id }} .
          
        
  
