name: Dotnetapplication
on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  DotnetInstall:
    name: Run dotnet on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Dotnet install
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
          cache: true
      - run: dotnet restore --locked-mode
          
  # Install_dependencies:
  #   runs-on: ubuntu-latest
  #   needs: DotnetInstall
  #   steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v4
       # - name: Installing dependency
       #   run: dotnet restore
          
        
  
